nodeVersion: 24.15.0
pmOnFail: download

catalog:
  '@types/node': ^26.1.2
  '@typescript/native': npm:typescript@7.0.2
  react: 19.3.0
  react-dom: 19.3.0
  typescript: npm:@typescript/typescript6@6.0.2

allowBuilds:
  esbuild: true
  oxc-resolver: true
  sharp: true
minimumReleaseAgeExclude:
  - '@seshuk/payload-plugin-tooling'
  - '@payloadcms/db-sqlite@4.0.0-canary.38'
  - '@payloadcms/drizzle@4.0.0-canary.38'
  - '@payloadcms/graphql@4.0.0-canary.38'
  - '@payloadcms/next@4.0.0-canary.38'
  - '@payloadcms/translations@4.0.0-canary.38'
  - '@payloadcms/ui@4.0.0-canary.38'
  - payload@4.0.0-canary.38
