overrides:
  '@typescript-eslint/eslint-plugin': ^8.57.0
  '@typescript-eslint/parser': ^8.57.0
  '@typescript-eslint/utils': ^8.57.0
  '@typescript-eslint/typescript-estree': ^8.57.0

allowBuilds:
  esbuild: true
  sharp: true
